name: Release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    Release:
        name: Release
        env:
            NPM_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v1
            - name: Install
              run: npm install&&npm install typescript -g
            - name: Build
              run: tsc
            - name: AUTH
              run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
            - name: Publish
              run: npm publish --access public   
